### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by SigmaMind-Research** [Friday-labs/radiox_frontend#10]
`radio@0.0.0 dev
vite

file:///home/xerxex/friday/git_repos/frontend/radiox_frontend/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
`
the app is not running at my local machine

**Comment by jaidevsairwa** [comment]
I am setting up using
"npm init vue@3"
Npm install
And it also uses vuetify so might have to add it manually if it's not showing in package.json

**Comment by SigmaMind-Research** [comment]
But it shows in dependencies of package.json

**Comment by jaidevsairwa** [comment]
I checked and most likely its cause of older version of node and npm, try updating node, I am currently using 18.6. For vue to work it has to be atleast v16 or higher

**Comment by SigmaMind-Research** [comment]
After updating node version it is working.
