### ISSUE TITLE
login api sign out not working 

### ISSUE THREAD

**Issue by jaidevsairwa** [Friday-labs/radiox_frontend#15]
@SigmaMind-Research

**Comment by SigmaMind-Research** [comment]
Logout route is working with redis service (cache service). without that it won't work.

**Comment by jaidevsairwa** [comment]
what type of auth is used for the service?  client can only pass token(s) in the form of variable in header whether it is from simple variable or redis key value.

**Comment by SigmaMind-Research** [comment]
@jaidevsairwa 

It's a bearer token. I updated the code, but I didn't deploy in production. Initially, I  will remove the redis service. So it does not look for blacklist token in cache.
