### ISSUE TITLE
/home api not working

### ISSUE THREAD

**Issue by jaidevsairwa** [Friday-labs/radiox_frontend#16]
response from postman:{
    "message": "The method is not allowed for the requested URL."
}
from api: "Missing Authorization Header"
from app: 308 permanent redirect
@SigmaMind-Research

**Comment by SigmaMind-Research** [comment]
The error is basically from the other reason, not because the token error @jaidevsairwa

**Comment by jaidevsairwa** [comment]
### **Input**
      const formimg = new FormData();
      formimg.append('xray_image',this.previewImage)

      axios({
        method: "post",
        url: 'https://radiox-api.wonderfulsea-1d4ac329.southeastasia.azurecontainerapps.io/home',
        data: formimg,
        headers: head0,
      })

**Comment by SigmaMind-Research** [comment]
@jaidevsairwa please include header "Bearer token_value"

**Comment by jaidevsairwa** [comment]
const authTkn = `Bearer ${(localStorage.getItem('token0'))}`;
      const head0 = {
        "content-type": 'multipart/form-data',
        "Authorization": authTkn
      };

**Comment by jaidevsairwa** [comment]
error: response: '{\n    "errors": {\n        "xray_image": "Missing required parameter in an uploaded file"\n    },\n    "message": "Input payload validation failed"\n}\n'
I have created new branch try running it.
I am not able to fix this issue 
file : rightbar.vue line 48
@SigmaMind-Research

**Comment by SigmaMind-Research** [comment]
@jaidevsairwa problem was in uplaodImage function. Look for warnings.

**Comment by jaidevsairwa** [comment]
home route resolved for mobile and desktop view
