### ISSUE TITLE
footer.vue page error

### ISSUE THREAD

**Issue by SigmaMind-Research** [Friday-labs/radiox_frontend#19]
@jaidevsairwa 
![Screenshot from 2023-07-31 14-15-12](https://github.com/SigmaMind-Research/radiox_frontend/assets/116866451/9514ef7e-626a-42a6-9006-6eb40db1e686)

**Comment by jaidevsairwa** [comment]
did you try to upload image first from right navigation instead of uploading from footer then submitted from mobile view
@SigmaMind-Research
