### ISSUE TITLE
too many warning in console

### ISSUE THREAD

**Issue by SigmaMind-Research** [Friday-labs/radiox_frontend#21]
@jaidevsairwa  @annavarughese

**Comment by jaidevsairwa** [comment]
Those warnings I showed are from Google auth window not app

**Comment by SigmaMind-Research** [comment]
![Screenshot from 2023-08-29 07-51-35](https://github.com/SigmaMind-Research/radiox_frontend/assets/116866451/3a1b791b-0b1f-4b2c-a5a2-15135a89dfa6)

**in login and singup page**

**Comment by SigmaMind-Research** [comment]
@annavarughese  both the UI is not responsive

**Comment by annavarughese** [comment]
resolved the warning
