### ISSUE TITLE
responsive error on login and main page

### ISSUE THREAD

**Issue by Gulshan-gaur** [Friday-labs/radiox_frontend#41]
@jaidevsairwa @annavarughese 
![Screenshot from 2023-11-11 19-14-47](https://github.com/SigmaMind-Research/radiox_frontend/assets/22424179/edb35f24-b789-45ed-ac2c-53201e8e2001)
![Screenshot from 2023-11-11 19-12-49](https://github.com/SigmaMind-Research/radiox_frontend/assets/22424179/32f46c1e-5f3c-4524-af19-8544df209c6b)

**Comment by jaidevsairwa** [comment]
added margin and minor css changes in login css
